# Generated by Django 4.1.3 on 2022-11-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('matricula', models.CharField(max_length=30)),
            ],
        ),
    ]
