# Generated by Django 4.1.3 on 2022-11-06 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Campus', '0001_initial'),
        ('Endereco', '0001_initial'),
        ('Aluno', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Campus.campus'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Endereco.endereco'),
        ),
    ]
