# Generated by Django 4.1.3 on 2022-11-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Disciplina', '0001_initial'),
        ('Aluno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('alunos', models.ManyToManyField(to='Aluno.aluno')),
                ('disciplinas', models.ManyToManyField(to='Disciplina.disciplina')),
            ],
        ),
    ]
