# Generated by Django 4.1.3 on 2022-11-06 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Endereco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=15, unique=True)),
                ('endereco', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Endereco.endereco')),
            ],
        ),
    ]
